### ISSUE TITLE
Problem with importing causaldata in Stata

### ISSUE THREAD

**Issue by saunokchakrabarty** [NickCH-K/causaldata#6]
Hi,

I have installed causaldata in Stata via "ssc install causaldata." When I run "causaldata social_insure.dta, use clear download", I get an error saying invalid 'Support'. Do you know how I can solve this issue? I am using Stata/SE 18.0.

Regards,
Saunok

**Comment by NickCH-K** [comment]
Hmm, I am not able to replicate the issue and it's not clear to me where it would be coming from. Do you have the same issue for other data sets?

**Comment by saunokchakrabarty** [comment]
Hi Nick,
I used "causaldata restaurant_inspections.dta, use clear download", and I got the same error. Not sure why. Is this a Stata issue?

Regards,
Saunok

**Comment by NickCH-K** [comment]
I'm wondering if it's a version thing. I have Stata 15.  For now, you can do "net get causaldata" to download all the data files as a ZIP

**Comment by saunokchakrabarty** [comment]
Hi Nick,
That worked. Thank you so much! 
I think it might be a version thing, but not sure.

Regards,
Saunok
