### ISSUE TITLE
Problem loading close_college dataset in Python

### ISSUE THREAD

**Issue by FemkeBakker** [NickCH-K/causaldata#7]
Hi @NickCH-K,

I'm having issues with loading the close_college dataset into Python. I get an attribute error saying that the model 'causaldata' has no attribute 'close_college'. Do you know what might be the issue?

It does work for other datasets, such as the black_politicians dataset. 

![image](https://github.com/NickCH-K/causaldata/assets/70972237/d44b1956-f624-4773-8e0a-9027a917f8fd)

Best,
Femke Bakker

**Comment by NickCH-K** [comment]
Thank you for letting me know about this. I will fix this soon. In the meantime you can find the file here and load it with pd.read_stata https://github.com/NickCH-K/causaldata/blob/main/Python/causaldata/close_college/close_college.dta

**Comment by NickCH-K** [comment]
Fixed
